cmd_drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o := /home/ridi/p123/p123/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/rtl8189fs/core/.rtw_btcoex.o.d  -nostdinc -isystem /home/ridi/p123/p123/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/../lib/gcc/arm-eabi/4.6.x-google/include -I/home/ridi/p123/p123/kernel_imx/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-mx6/include -Iarch/arm/plat-mxc/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -O1 -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -Idrivers/net/wireless/rtl8189fs/include -Idrivers/net/wireless/rtl8189fs/hal/phydm -Idrivers/net/wireless/rtl8189fs/platform -DCONFIG_RTL8188F -DCONFIG_MP_INCLUDED -DCONFIG_POWER_SAVING -DCONFIG_TRAFFIC_PROTECT -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DREALTEK_CONFIG_PATH=\"\" -DCONFIG_TXPWR_BY_RATE_EN=1 -DCONFIG_TXPWR_LIMIT_EN=1 -DCONFIG_RTW_ADAPTIVITY_EN=1 -DCONFIG_RTW_ADAPTIVITY_MODE=0 -DCONFIG_WOWLAN -DCONFIG_RTW_SDIO_PM_KEEP_POWER -DCONFIG_GPIO_WAKEUP -DHIGH_ACTIVE=0 -DCONFIG_RTW_SDIO_PM_KEEP_POWER -DCONFIG_BR_EXT '-DCONFIG_BR_EXT_BRNAME="'br0'"' -DDM_ODM_SUPPORT_TYPE=0x04 -DCONFIG_LITTLE_ENDIAN -DCONFIG_IOCTL_CFG80211 -DRTW_ENABLE_WIFI_CONTROL_FUNC -DCONFIG_CONCURRENT_MODE  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rtw_btcoex)"  -D"KBUILD_MODNAME=KBUILD_STR(8189fs)" -c -o drivers/net/wireless/rtl8189fs/core/.tmp_rtw_btcoex.o drivers/net/wireless/rtl8189fs/core/rtw_btcoex.c

source_drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o := drivers/net/wireless/rtl8189fs/core/rtw_btcoex.c

deps_drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o := \
    $(wildcard include/config/bt/coexist.h) \
    $(wildcard include/config/bt/coexist/socket/trx.h) \
    $(wildcard include/config/concurrent/mode.h) \
    $(wildcard include/config/error/reset.h) \

drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o: $(deps_drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o)

$(deps_drivers/net/wireless/rtl8189fs/core/rtw_btcoex.o):
